"""empty message

Revision ID: 344870b463c9
Revises: 
Create Date: 2021-04-06 18:46:12.182011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344870b463c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Artist', sa.Column('seekingDescription', sa.String(length=500), nullable=True))
    op.add_column('Artist', sa.Column('seekingVenue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('upcoming_counter', sa.Integer(), nullable=True))
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'upcoming_shows_count')
    op.drop_column('Artist', 'seeking_venue')
    op.add_column('Venue', sa.Column('seekingDescription', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('upcoming_counter', sa.Integer(), nullable=True))
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'upcoming_shows_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('upcoming_shows_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'upcoming_counter')
    op.drop_column('Venue', 'seekingDescription')
    op.add_column('Artist', sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('upcoming_shows_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'upcoming_counter')
    op.drop_column('Artist', 'seekingVenue')
    op.drop_column('Artist', 'seekingDescription')
    op.drop_table('Show')
    # ### end Alembic commands ###
